"""
Frozen Evaluation Protocol (self-contained, stdlib only).

Purpose
-------
Break the repeated-failure loop ("冻结评测协议与基线") by removing the
dependency on files outside the sandbox. Everything needed to evaluate a
bin-packing candidate is defined here and is deterministic.

Protocol definition (FROZEN)
----------------------------
- Problem: 1-D bin packing, capacity C = 100.
- Instance generator: deterministic, seeded by instance id.
- Metric: bins_used (lower is better). Score = mean over suite of
  (baseline_bins - candidate_bins) / baseline_bins  (relative improvement).
- Tie-break: fewer bins; then lexicographically smaller placement signature.
- Suite: 60 instances, ids 0..59, generated by make_suite().
- Baseline: First-Fit-Decreasing (FFD), frozen in baseline.py.

Any change to capacity, generator, metric, or suite size is a protocol
change and MUST bump PROTOCOL_VERSION.
"""

PROTOCOL_VERSION = "1.0.0"
CAPACITY = 100
SUITE_SIZE = 60


def make_instance(i, capacity=CAPACITY):
    """Deterministic instance generator. Returns list[int] item sizes in (0, capacity]."""
    # xorshift-style LCG, fully deterministic, no external deps
    state = (i * 2654435761 + 1013904223) & 0xFFFFFFFF
    n = 20 + (state % 41)  # 20..60 items
    items = []
    for k in range(n):
        state = (state * 1103515245 + 12345) & 0x7FFFFFFF
        size = 1 + (state % capacity)  # 1..capacity
        items.append(size)
    return items


def make_suite(size=SUITE_SIZE, capacity=CAPACITY):
    return [make_instance(i, capacity) for i in range(size)]


def ffd(items, capacity=CAPACITY):
    """First-Fit-Decreasing. Deterministic baseline."""
    bins = []  # list of remaining capacities
    for size in sorted(items, reverse=True):
        placed = False
        for b in range(len(bins)):
            if bins[b] >= size:
                bins[b] -= size
                placed = True
                break
        if not placed:
            bins.append(capacity - size)
    return len(bins)


def lower_bound(items, capacity=CAPACITY):
    """Simple lower bound: max(ceil(total/capacity), max item == capacity ? 1 : 0)."""
    total = sum(items)
    lb = (total + capacity - 1) // capacity
    if any(s == capacity for s in items):
        lb = max(lb, 1)
    return lb


def validate_instance(items, capacity=CAPACITY):
    assert isinstance(items, list) and items, "instance must be non-empty list"
    for s in items:
        assert isinstance(s, int) and 0 < s <= capacity, f"bad item size {s}"
    return True


def protocol_fingerprint():
    """Stable fingerprint of the frozen protocol (for regression detection)."""
    import hashlib
    h = hashlib.sha256()
    h.update(PROTOCOL_VERSION.encode())
    h.update(str(CAPACITY).encode())
    h.update(str(SUITE_SIZE).encode())
    for inst in make_suite():
        h.update(",".join(map(str, inst)).encode())
        h.update(b"|")
    return h.hexdigest()
